backend:
  name: github
  branch: main 
  repo: davechekan/docu-site
  squash_merges: true

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow

collections:
- name: blog
  label: "blog"
  folder: blog
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"
    - label: "Authors"
      name: "authors" 
      widget: "list"
      fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string } 
        - { name: url, label: URL, widget: string } 
        - { name: imageUrl, label: ImageURL, widget: string } 
- name: docs
  label: "next version docs"
  folder: docs
  path: '{{section}}/{{slug}}'
  create: true
  extension: md
  identifier_field: sidebar_label
  nested:
    depth: 100
    summary: '{{title}}'
  fields:
    - { name: sidebar_label, label: Title, widget: string } 
    - { name: sidebar_position, label: Sidebar Position, widget: number }
    - { name: section, label: Section, widget: string}
    - { name: body, label: Body, widget: markdown }

- name: versioned_docs
  label: "current versioned docs"
  folder: versioned_docs
  path: '{{section}}/{{slug}}'
  create: true
  extension: md
  identifier_field: sidebar_label
  nested:
    depth: 100
    summary: '{{title}}'
  fields:
    - { name: sidebar_label, label: Title, widget: string } 
    - { name: sidebar_position, label: Sidebar Position, widget: number }
    - { name: section, label: Section, widget: string}
    - { name: body, label: Body, widget: markdown }